//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jilipe.DataAccess.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvestmentCycle
    {
        public int Id { get; set; }
        public System.DateTime FromDate { get; set; }
        public int ProductId { get; set; }
        public decimal TargetAmount { get; set; }
        public decimal MinimumAmount { get; set; }
        public decimal MaximumAmount { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
